<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CleanArch.ArchitectureTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="xunit" Version="2.7.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.7" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\Domain\CleanArch.Domain.csproj" />
    <ProjectReference Include="..\..\src\Core\Application\CleanArch.Application.csproj" />
    <ProjectReference Include="..\..\src\External\Infrastructure\CleanArch.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\External\Presentation\CleanArch.Presentation.csproj" />
  </ItemGroup>

</Project>
