// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CleanArch.BddTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TenantRegistrationFeature : object, Xunit.IClassFixture<TenantRegistrationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TenantRegistration.feature"
#line hidden
        
        public TenantRegistrationFeature(TenantRegistrationFeature.FixtureData fixtureData, CleanArch_BddTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "Tenant Registration", "    As a platform administrator\n    I want to register new tenants\n    So that or" +
                    "ganizations can use the platform", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
    #line hidden
#line 7
        testRunner.Given("the tenant repository is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successfully register a new tenant with default tier")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Registration")]
        [Xunit.TraitAttribute("Description", "Successfully register a new tenant with default tier")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        public void SuccessfullyRegisterANewTenantWithDefaultTier()
        {
            string[] tagsOfScenario = new string[] {
                    "registration",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfully register a new tenant with default tier", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table4.AddRow(new string[] {
                            "Identifier",
                            "acme-corp"});
                table4.AddRow(new string[] {
                            "Name",
                            "Acme Corporation"});
                table4.AddRow(new string[] {
                            "ContactEmail",
                            "admin@acme.com"});
                table4.AddRow(new string[] {
                            "AdminName",
                            "John Smith"});
                table4.AddRow(new string[] {
                            "Description",
                            "Primary account"});
#line 11
        testRunner.Given("I have tenant registration details:", ((string)(null)), table4, "Given ");
#line hidden
#line 18
        testRunner.When("I register the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 19
        testRunner.Then("the tenant should be created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 20
        testRunner.And("the tenant identifier should be \"acme-corp\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
        testRunner.And("the tenant name should be \"Acme Corporation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
        testRunner.And("the tenant subscription tier should be \"Free\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
        testRunner.And("the tenant status should be \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 24
        testRunner.And("a TenantRegistered domain event should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 25
        testRunner.And("a TenantActivated domain event should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Register a tenant with a specific subscription tier")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Registration")]
        [Xunit.TraitAttribute("Description", "Register a tenant with a specific subscription tier")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        public void RegisterATenantWithASpecificSubscriptionTier()
        {
            string[] tagsOfScenario = new string[] {
                    "registration",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register a tenant with a specific subscription tier", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table5.AddRow(new string[] {
                            "Identifier",
                            "enterprise-co"});
                table5.AddRow(new string[] {
                            "Name",
                            "Enterprise Co"});
                table5.AddRow(new string[] {
                            "ContactEmail",
                            "admin@enterprise.com"});
#line 29
        testRunner.Given("I have tenant registration details:", ((string)(null)), table5, "Given ");
#line hidden
#line 34
        testRunner.And("the subscription tier is \"Enterprise\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
        testRunner.When("I register the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
        testRunner.Then("the tenant should be created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
        testRunner.And("the tenant subscription tier should be \"Enterprise\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
        testRunner.And("the tenant max users should be unlimited", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Register a tenant without auto-activation")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Registration")]
        [Xunit.TraitAttribute("Description", "Register a tenant without auto-activation")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        public void RegisterATenantWithoutAuto_Activation()
        {
            string[] tagsOfScenario = new string[] {
                    "registration",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register a tenant without auto-activation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table6.AddRow(new string[] {
                            "Identifier",
                            "pending-org"});
                table6.AddRow(new string[] {
                            "Name",
                            "Pending Org"});
                table6.AddRow(new string[] {
                            "ContactEmail",
                            "admin@pending.org"});
#line 42
        testRunner.Given("I have tenant registration details:", ((string)(null)), table6, "Given ");
#line hidden
#line 47
        testRunner.And("auto-activation is disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 48
        testRunner.When("I register the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 49
        testRunner.Then("the tenant should be created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
        testRunner.And("the tenant status should be \"Provisioning\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
        testRunner.And("only a TenantRegistered domain event should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject registration with duplicate identifier")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Registration")]
        [Xunit.TraitAttribute("Description", "Reject registration with duplicate identifier")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "validation")]
        public void RejectRegistrationWithDuplicateIdentifier()
        {
            string[] tagsOfScenario = new string[] {
                    "registration",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject registration with duplicate identifier", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 55
        testRunner.Given("a tenant with identifier \"acme-corp\" already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table7.AddRow(new string[] {
                            "Identifier",
                            "acme-corp"});
                table7.AddRow(new string[] {
                            "Name",
                            "Another Acme"});
                table7.AddRow(new string[] {
                            "ContactEmail",
                            "other@acme.com"});
#line 56
        testRunner.And("I have tenant registration details:", ((string)(null)), table7, "And ");
#line hidden
#line 61
        testRunner.When("I register the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 62
        testRunner.Then("the registration should fail with error \"Tenant.DuplicateIdentifier\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject registration with empty identifier")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Registration")]
        [Xunit.TraitAttribute("Description", "Reject registration with empty identifier")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "validation")]
        public void RejectRegistrationWithEmptyIdentifier()
        {
            string[] tagsOfScenario = new string[] {
                    "registration",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject registration with empty identifier", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table8.AddRow(new string[] {
                            "Identifier",
                            ""});
                table8.AddRow(new string[] {
                            "Name",
                            "Some Corp"});
                table8.AddRow(new string[] {
                            "ContactEmail",
                            "admin@some.com"});
#line 66
        testRunner.Given("I have tenant registration details:", ((string)(null)), table8, "Given ");
#line hidden
#line 71
        testRunner.When("I attempt to register the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 72
        testRunner.Then("it should throw an ArgumentException for \"identifier\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject registration with empty name")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Registration")]
        [Xunit.TraitAttribute("Description", "Reject registration with empty name")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "validation")]
        public void RejectRegistrationWithEmptyName()
        {
            string[] tagsOfScenario = new string[] {
                    "registration",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject registration with empty name", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table9.AddRow(new string[] {
                            "Identifier",
                            "some-corp"});
                table9.AddRow(new string[] {
                            "Name",
                            ""});
                table9.AddRow(new string[] {
                            "ContactEmail",
                            "admin@some.com"});
#line 76
        testRunner.Given("I have tenant registration details:", ((string)(null)), table9, "Given ");
#line hidden
#line 81
        testRunner.When("I attempt to register the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 82
        testRunner.Then("it should throw an ArgumentException for \"name\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject registration with empty email")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Registration")]
        [Xunit.TraitAttribute("Description", "Reject registration with empty email")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "validation")]
        public void RejectRegistrationWithEmptyEmail()
        {
            string[] tagsOfScenario = new string[] {
                    "registration",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject registration with empty email", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table10.AddRow(new string[] {
                            "Identifier",
                            "some-corp"});
                table10.AddRow(new string[] {
                            "Name",
                            "Some Corp"});
                table10.AddRow(new string[] {
                            "ContactEmail",
                            ""});
#line 86
        testRunner.Given("I have tenant registration details:", ((string)(null)), table10, "Given ");
#line hidden
#line 91
        testRunner.When("I attempt to register the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 92
        testRunner.Then("it should throw an ArgumentException for \"contactEmail\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Identifier is normalized to lowercase")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Registration")]
        [Xunit.TraitAttribute("Description", "Identifier is normalized to lowercase")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "identifier-format")]
        public void IdentifierIsNormalizedToLowercase()
        {
            string[] tagsOfScenario = new string[] {
                    "registration",
                    "identifier-format"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Identifier is normalized to lowercase", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table11.AddRow(new string[] {
                            "Identifier",
                            "ACME-Corp"});
                table11.AddRow(new string[] {
                            "Name",
                            "Acme Corporation"});
                table11.AddRow(new string[] {
                            "ContactEmail",
                            "admin@acme.com"});
#line 96
        testRunner.Given("I have tenant registration details:", ((string)(null)), table11, "Given ");
#line hidden
#line 101
        testRunner.When("I register the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 102
        testRunner.Then("the tenant identifier should be \"acme-corp\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Contact email is normalized to lowercase")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Registration")]
        [Xunit.TraitAttribute("Description", "Contact email is normalized to lowercase")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "email-format")]
        public void ContactEmailIsNormalizedToLowercase()
        {
            string[] tagsOfScenario = new string[] {
                    "registration",
                    "email-format"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Contact email is normalized to lowercase", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table12.AddRow(new string[] {
                            "Identifier",
                            "test-corp"});
                table12.AddRow(new string[] {
                            "Name",
                            "Test Corp"});
                table12.AddRow(new string[] {
                            "ContactEmail",
                            "Admin@Test.COM"});
#line 106
        testRunner.Given("I have tenant registration details:", ((string)(null)), table12, "Given ");
#line hidden
#line 111
        testRunner.When("I register the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 112
        testRunner.Then("the tenant contact email should be \"admin@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TenantRegistrationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TenantRegistrationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
