// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CleanArch.BddTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TenantSubscriptionManagementFeature : object, Xunit.IClassFixture<TenantSubscriptionManagementFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TenantSubscription.feature"
#line hidden
        
        public TenantSubscriptionManagementFeature(TenantSubscriptionManagementFeature.FixtureData fixtureData, CleanArch_BddTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "Tenant Subscription Management", "    As a platform administrator\n    I want to manage tenant subscription tiers\n  " +
                    "  So that tenants get appropriate resource limits", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
    #line hidden
#line 7
        testRunner.Given("a tenant \"startup-inc\" exists with tier \"Free\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Upgrade from Free to Professional")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Subscription Management")]
        [Xunit.TraitAttribute("Description", "Upgrade from Free to Professional")]
        [Xunit.TraitAttribute("Category", "subscription")]
        [Xunit.TraitAttribute("Category", "tier-change")]
        public void UpgradeFromFreeToProfessional()
        {
            string[] tagsOfScenario = new string[] {
                    "subscription",
                    "tier-change"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Upgrade from Free to Professional", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 11
        testRunner.When("I change the subscription to \"Professional\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
        testRunner.Then("the tenant subscription tier should be \"Professional\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 13
        testRunner.And("the tenant max users should be 100", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
        testRunner.And("the tenant max storage should be 50000 MB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
        testRunner.And("the tenant max API calls should be 100000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
        testRunner.And("a TenantSubscriptionChanged domain event should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Downgrade from Professional to Starter")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Subscription Management")]
        [Xunit.TraitAttribute("Description", "Downgrade from Professional to Starter")]
        [Xunit.TraitAttribute("Category", "subscription")]
        [Xunit.TraitAttribute("Category", "tier-change")]
        public void DowngradeFromProfessionalToStarter()
        {
            string[] tagsOfScenario = new string[] {
                    "subscription",
                    "tier-change"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Downgrade from Professional to Starter", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 20
        testRunner.Given("the tenant tier is \"Professional\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 21
        testRunner.When("I change the subscription to \"Starter\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
        testRunner.Then("the tenant subscription tier should be \"Starter\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 23
        testRunner.And("the tenant max users should be 25", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 24
        testRunner.And("the tenant max storage should be 5000 MB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 25
        testRunner.And("the tenant max API calls should be 10000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 26
        testRunner.And("a TenantSubscriptionChanged domain event should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Upgrade to Enterprise gives unlimited resources")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Subscription Management")]
        [Xunit.TraitAttribute("Description", "Upgrade to Enterprise gives unlimited resources")]
        [Xunit.TraitAttribute("Category", "subscription")]
        [Xunit.TraitAttribute("Category", "tier-change")]
        public void UpgradeToEnterpriseGivesUnlimitedResources()
        {
            string[] tagsOfScenario = new string[] {
                    "subscription",
                    "tier-change"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Upgrade to Enterprise gives unlimited resources", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 30
        testRunner.When("I change the subscription to \"Enterprise\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 31
        testRunner.Then("the tenant subscription tier should be \"Enterprise\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
        testRunner.And("the tenant max users should be unlimited", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 33
        testRunner.And("the tenant max storage should be unlimited", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
        testRunner.And("the tenant max API calls should be unlimited", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Set subscription expiry date")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Subscription Management")]
        [Xunit.TraitAttribute("Description", "Set subscription expiry date")]
        [Xunit.TraitAttribute("Category", "subscription")]
        [Xunit.TraitAttribute("Category", "expiry")]
        public void SetSubscriptionExpiryDate()
        {
            string[] tagsOfScenario = new string[] {
                    "subscription",
                    "expiry"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Set subscription expiry date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 38
        testRunner.When("I change the subscription to \"Professional\" with expiry \"2030-12-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 39
        testRunner.Then("the subscription expiry date should be \"2030-12-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
        testRunner.And("the tenant should not be expired", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Expired subscription is detected")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Subscription Management")]
        [Xunit.TraitAttribute("Description", "Expired subscription is detected")]
        [Xunit.TraitAttribute("Category", "subscription")]
        [Xunit.TraitAttribute("Category", "expiry")]
        public void ExpiredSubscriptionIsDetected()
        {
            string[] tagsOfScenario = new string[] {
                    "subscription",
                    "expiry"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Expired subscription is detected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 44
        testRunner.When("I change the subscription to \"Professional\" with expiry \"2020-01-01\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 45
        testRunner.Then("the tenant should be expired", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Changing to the same tier does not raise event")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Subscription Management")]
        [Xunit.TraitAttribute("Description", "Changing to the same tier does not raise event")]
        [Xunit.TraitAttribute("Category", "subscription")]
        [Xunit.TraitAttribute("Category", "no-change")]
        public void ChangingToTheSameTierDoesNotRaiseEvent()
        {
            string[] tagsOfScenario = new string[] {
                    "subscription",
                    "no-change"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Changing to the same tier does not raise event", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 49
        testRunner.When("I change the subscription to \"Free\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 50
        testRunner.Then("no subscription changed event should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Resource limits match tier defaults")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Subscription Management")]
        [Xunit.TraitAttribute("Description", "Resource limits match tier defaults")]
        [Xunit.TraitAttribute("Category", "subscription")]
        [Xunit.TraitAttribute("Category", "resource-limits")]
        [Xunit.InlineDataAttribute("Free", "5", "500", "1000", "3", new string[0])]
        [Xunit.InlineDataAttribute("Starter", "25", "5000", "10000", "20", new string[0])]
        [Xunit.InlineDataAttribute("Professional", "100", "50000", "100000", "100", new string[0])]
        public void ResourceLimitsMatchTierDefaults(string tier, string maxUsers, string maxStorageMb, string maxApiCalls, string maxWorkspaces, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "subscription",
                    "resource-limits"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Tier", tier);
            argumentsOfScenario.Add("MaxUsers", maxUsers);
            argumentsOfScenario.Add("MaxStorageMb", maxStorageMb);
            argumentsOfScenario.Add("MaxApiCalls", maxApiCalls);
            argumentsOfScenario.Add("MaxWorkspaces", maxWorkspaces);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Resource limits match tier defaults", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 54
        testRunner.When(string.Format("I change the subscription to \"{0}\"", tier), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
        testRunner.Then(string.Format("the tenant max users should be {0}", maxUsers), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 56
        testRunner.And(string.Format("the tenant max storage should be {0} MB", maxStorageMb), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
        testRunner.And(string.Format("the tenant max API calls should be {0}", maxApiCalls), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
        testRunner.And(string.Format("the tenant max workspaces should be {0}", maxWorkspaces), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TenantSubscriptionManagementFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TenantSubscriptionManagementFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
