// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CleanArch.BddTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TenantFeatureFlagsFeature : object, Xunit.IClassFixture<TenantFeatureFlagsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TenantFeatureFlags.feature"
#line hidden
        
        public TenantFeatureFlagsFeature(TenantFeatureFlagsFeature.FixtureData fixtureData, CleanArch_BddTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "Tenant Feature Flags", "    As a platform administrator\n    I want to configure feature flags per tenant\n" +
                    "    So that I can control feature access granularly", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
    #line hidden
#line 7
        testRunner.Given("a tenant \"feature-corp\" exists with status \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Enable a feature for a tenant")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Feature Flags")]
        [Xunit.TraitAttribute("Description", "Enable a feature for a tenant")]
        [Xunit.TraitAttribute("Category", "features")]
        [Xunit.TraitAttribute("Category", "enable")]
        public void EnableAFeatureForATenant()
        {
            string[] tagsOfScenario = new string[] {
                    "features",
                    "enable"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Enable a feature for a tenant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 11
        testRunner.When("I enable feature \"api_access\" for the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
        testRunner.Then("the tenant should have feature \"api_access\" enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 13
        testRunner.And("the tenant should have 1 feature configured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Enable a feature with expiry date")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Feature Flags")]
        [Xunit.TraitAttribute("Description", "Enable a feature with expiry date")]
        [Xunit.TraitAttribute("Category", "features")]
        [Xunit.TraitAttribute("Category", "enable")]
        [Xunit.TraitAttribute("Category", "expiry")]
        public void EnableAFeatureWithExpiryDate()
        {
            string[] tagsOfScenario = new string[] {
                    "features",
                    "enable",
                    "expiry"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Enable a feature with expiry date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 17
        testRunner.When("I enable feature \"advanced_reporting\" with expiry \"2030-12-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 18
        testRunner.Then("the tenant should have feature \"advanced_reporting\" enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
        testRunner.And("the feature \"advanced_reporting\" should expire on \"2030-12-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Disable a feature for a tenant")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Feature Flags")]
        [Xunit.TraitAttribute("Description", "Disable a feature for a tenant")]
        [Xunit.TraitAttribute("Category", "features")]
        [Xunit.TraitAttribute("Category", "disable")]
        public void DisableAFeatureForATenant()
        {
            string[] tagsOfScenario = new string[] {
                    "features",
                    "disable"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disable a feature for a tenant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 23
        testRunner.Given("the tenant has feature \"api_access\" enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 24
        testRunner.When("I disable feature \"api_access\" for the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 25
        testRunner.Then("the tenant should not have feature \"api_access\" active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Enabling an already enabled feature updates expiry")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Feature Flags")]
        [Xunit.TraitAttribute("Description", "Enabling an already enabled feature updates expiry")]
        [Xunit.TraitAttribute("Category", "features")]
        [Xunit.TraitAttribute("Category", "enable")]
        [Xunit.TraitAttribute("Category", "idempotent")]
        public void EnablingAnAlreadyEnabledFeatureUpdatesExpiry()
        {
            string[] tagsOfScenario = new string[] {
                    "features",
                    "enable",
                    "idempotent"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Enabling an already enabled feature updates expiry", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 29
        testRunner.Given("the tenant has feature \"sso_integration\" enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 30
        testRunner.When("I enable feature \"sso_integration\" with expiry \"2030-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 31
        testRunner.Then("the feature \"sso_integration\" should expire on \"2030-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
        testRunner.And("the tenant should have 1 feature configured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="HasFeature returns false for disabled feature")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Feature Flags")]
        [Xunit.TraitAttribute("Description", "HasFeature returns false for disabled feature")]
        [Xunit.TraitAttribute("Category", "features")]
        [Xunit.TraitAttribute("Category", "check")]
        public void HasFeatureReturnsFalseForDisabledFeature()
        {
            string[] tagsOfScenario = new string[] {
                    "features",
                    "check"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HasFeature returns false for disabled feature", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 36
        testRunner.Given("the tenant has feature \"audit_log\" disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 37
        testRunner.When("I check if the tenant has feature \"audit_log\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
        testRunner.Then("the result should be false", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="HasFeature returns false for expired feature")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Feature Flags")]
        [Xunit.TraitAttribute("Description", "HasFeature returns false for expired feature")]
        [Xunit.TraitAttribute("Category", "features")]
        [Xunit.TraitAttribute("Category", "check")]
        public void HasFeatureReturnsFalseForExpiredFeature()
        {
            string[] tagsOfScenario = new string[] {
                    "features",
                    "check"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HasFeature returns false for expired feature", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 42
        testRunner.Given("the tenant has feature \"bulk_operations\" with past expiry", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 43
        testRunner.When("I check if the tenant has feature \"bulk_operations\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 44
        testRunner.Then("the result should be false", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="HasFeature returns true for active non-expired feature")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Feature Flags")]
        [Xunit.TraitAttribute("Description", "HasFeature returns true for active non-expired feature")]
        [Xunit.TraitAttribute("Category", "features")]
        [Xunit.TraitAttribute("Category", "check")]
        public void HasFeatureReturnsTrueForActiveNon_ExpiredFeature()
        {
            string[] tagsOfScenario = new string[] {
                    "features",
                    "check"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HasFeature returns true for active non-expired feature", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 48
        testRunner.Given("the tenant has feature \"data_export\" enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 49
        testRunner.When("I check if the tenant has feature \"data_export\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 50
        testRunner.Then("the result should be true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Multiple features can be configured independently")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Feature Flags")]
        [Xunit.TraitAttribute("Description", "Multiple features can be configured independently")]
        [Xunit.TraitAttribute("Category", "features")]
        [Xunit.TraitAttribute("Category", "multiple")]
        public void MultipleFeaturesCanBeConfiguredIndependently()
        {
            string[] tagsOfScenario = new string[] {
                    "features",
                    "multiple"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple features can be configured independently", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 54
        testRunner.When("I enable feature \"api_access\" for the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
        testRunner.And("I enable feature \"sso_integration\" for the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
        testRunner.And("I enable feature \"webhook_integration\" for the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
        testRunner.Then("the tenant should have 3 features configured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 58
        testRunner.And("the tenant should have feature \"api_access\" enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 59
        testRunner.And("the tenant should have feature \"sso_integration\" enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 60
        testRunner.And("the tenant should have feature \"webhook_integration\" enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Enable feature with empty code throws exception")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Feature Flags")]
        [Xunit.TraitAttribute("Description", "Enable feature with empty code throws exception")]
        [Xunit.TraitAttribute("Category", "features")]
        [Xunit.TraitAttribute("Category", "validation")]
        public void EnableFeatureWithEmptyCodeThrowsException()
        {
            string[] tagsOfScenario = new string[] {
                    "features",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Enable feature with empty code throws exception", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 64
        testRunner.When("I attempt to enable feature \"\" for the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 65
        testRunner.Then("it should throw an ArgumentException for \"featureCode\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TenantFeatureFlagsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TenantFeatureFlagsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
