// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CleanArch.BddTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TenantProfileManagementFeature : object, Xunit.IClassFixture<TenantProfileManagementFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TenantProfile.feature"
#line hidden
        
        public TenantProfileManagementFeature(TenantProfileManagementFeature.FixtureData fixtureData, CleanArch_BddTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "Tenant Profile Management", "    As a platform administrator\n    I want to update tenant profile information\n " +
                    "   So that tenant details stay current and accurate", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
    #line hidden
#line 7
        testRunner.Given("a tenant \"profile-corp\" exists with name \"Profile Corp\" and email \"admin@profile." +
                    "com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update tenant profile name and description")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Profile Management")]
        [Xunit.TraitAttribute("Description", "Update tenant profile name and description")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "update")]
        public void UpdateTenantProfileNameAndDescription()
        {
            string[] tagsOfScenario = new string[] {
                    "profile",
                    "update"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update tenant profile name and description", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "Name",
                            "Profile Corporation"});
                table2.AddRow(new string[] {
                            "Description",
                            "Updated company description"});
                table2.AddRow(new string[] {
                            "ContactEmail",
                            "admin@profile.com"});
#line 11
        testRunner.When("I update the tenant profile:", ((string)(null)), table2, "When ");
#line hidden
#line 16
        testRunner.Then("the tenant name should be \"Profile Corporation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
        testRunner.And("the tenant description should be \"Updated company description\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update tenant contact email")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Profile Management")]
        [Xunit.TraitAttribute("Description", "Update tenant contact email")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "update")]
        public void UpdateTenantContactEmail()
        {
            string[] tagsOfScenario = new string[] {
                    "profile",
                    "update"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update tenant contact email", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table3.AddRow(new string[] {
                            "Name",
                            "Profile Corp"});
                table3.AddRow(new string[] {
                            "ContactEmail",
                            "new-admin@profile.com"});
#line 21
        testRunner.When("I update the tenant profile:", ((string)(null)), table3, "When ");
#line hidden
#line 25
        testRunner.Then("the tenant contact email should be \"new-admin@profile.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Set custom domain for tenant")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Profile Management")]
        [Xunit.TraitAttribute("Description", "Set custom domain for tenant")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "custom-domain")]
        public void SetCustomDomainForTenant()
        {
            string[] tagsOfScenario = new string[] {
                    "profile",
                    "custom-domain"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Set custom domain for tenant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 29
        testRunner.When("I set the custom domain to \"app.profile-corp.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
        testRunner.Then("the tenant custom domain should be \"app.profile-corp.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Remove custom domain")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Profile Management")]
        [Xunit.TraitAttribute("Description", "Remove custom domain")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "custom-domain")]
        public void RemoveCustomDomain()
        {
            string[] tagsOfScenario = new string[] {
                    "profile",
                    "custom-domain"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove custom domain", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 34
        testRunner.Given("the tenant has custom domain \"app.profile-corp.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 35
        testRunner.When("I set the custom domain to null", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
        testRunner.Then("the tenant custom domain should be null", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Set tenant logo URL")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Profile Management")]
        [Xunit.TraitAttribute("Description", "Set tenant logo URL")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "logo")]
        public void SetTenantLogoURL()
        {
            string[] tagsOfScenario = new string[] {
                    "profile",
                    "logo"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Set tenant logo URL", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 40
        testRunner.When("I set the logo URL to \"https://cdn.example.com/logos/profile-corp.png\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 41
        testRunner.Then("the tenant logo URL should be \"https://cdn.example.com/logos/profile-corp.png\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Set tenant-specific connection string")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Profile Management")]
        [Xunit.TraitAttribute("Description", "Set tenant-specific connection string")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "connection-string")]
        public void SetTenant_SpecificConnectionString()
        {
            string[] tagsOfScenario = new string[] {
                    "profile",
                    "connection-string"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Set tenant-specific connection string", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 45
        testRunner.When("I set the connection string to \"Server=tenant-db;Database=ProfileCorp\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
        testRunner.Then("the tenant connection string should be \"Server=tenant-db;Database=ProfileCorp\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update profile with empty name throws exception")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Profile Management")]
        [Xunit.TraitAttribute("Description", "Update profile with empty name throws exception")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "validation")]
        public void UpdateProfileWithEmptyNameThrowsException()
        {
            string[] tagsOfScenario = new string[] {
                    "profile",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update profile with empty name throws exception", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 50
        testRunner.When("I attempt to update the tenant profile with empty name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 51
        testRunner.Then("it should throw an ArgumentException for \"name\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update profile with empty email throws exception")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Profile Management")]
        [Xunit.TraitAttribute("Description", "Update profile with empty email throws exception")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "validation")]
        public void UpdateProfileWithEmptyEmailThrowsException()
        {
            string[] tagsOfScenario = new string[] {
                    "profile",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update profile with empty email throws exception", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 55
        testRunner.When("I attempt to update the tenant profile with empty email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 56
        testRunner.Then("it should throw an ArgumentException for \"contactEmail\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Custom domain is normalized to lowercase")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Profile Management")]
        [Xunit.TraitAttribute("Description", "Custom domain is normalized to lowercase")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "normalization")]
        public void CustomDomainIsNormalizedToLowercase()
        {
            string[] tagsOfScenario = new string[] {
                    "profile",
                    "normalization"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Custom domain is normalized to lowercase", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 59
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 60
        testRunner.When("I set the custom domain to \"App.Profile-Corp.COM\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 61
        testRunner.Then("the tenant custom domain should be \"app.profile-corp.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TenantProfileManagementFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TenantProfileManagementFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
