// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CleanArch.BddTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TenantLifecycleManagementFeature : object, Xunit.IClassFixture<TenantLifecycleManagementFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TenantLifecycle.feature"
#line hidden
        
        public TenantLifecycleManagementFeature(TenantLifecycleManagementFeature.FixtureData fixtureData, CleanArch_BddTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "Tenant Lifecycle Management", "    As a platform administrator\n    I want to manage tenant lifecycle states\n    " +
                    "So that I can control tenant access to the platform", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
    #line hidden
#line 7
        testRunner.Given("a tenant \"acme-corp\" exists with status \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Activate a provisioning tenant")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Lifecycle Management")]
        [Xunit.TraitAttribute("Description", "Activate a provisioning tenant")]
        [Xunit.TraitAttribute("Category", "lifecycle")]
        [Xunit.TraitAttribute("Category", "activation")]
        public void ActivateAProvisioningTenant()
        {
            string[] tagsOfScenario = new string[] {
                    "lifecycle",
                    "activation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Activate a provisioning tenant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 11
        testRunner.Given("the tenant status is \"Provisioning\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 12
        testRunner.When("I activate the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
        testRunner.Then("the tenant status should be \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 14
        testRunner.And("the activation date should be set", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
        testRunner.And("a TenantActivated domain event should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Activating an already active tenant is idempotent")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Lifecycle Management")]
        [Xunit.TraitAttribute("Description", "Activating an already active tenant is idempotent")]
        [Xunit.TraitAttribute("Category", "lifecycle")]
        [Xunit.TraitAttribute("Category", "activation")]
        public void ActivatingAnAlreadyActiveTenantIsIdempotent()
        {
            string[] tagsOfScenario = new string[] {
                    "lifecycle",
                    "activation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Activating an already active tenant is idempotent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 19
        testRunner.When("I activate the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
        testRunner.Then("the tenant status should be \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 21
        testRunner.And("no additional domain events should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reactivate a suspended tenant")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Lifecycle Management")]
        [Xunit.TraitAttribute("Description", "Reactivate a suspended tenant")]
        [Xunit.TraitAttribute("Category", "lifecycle")]
        [Xunit.TraitAttribute("Category", "activation")]
        public void ReactivateASuspendedTenant()
        {
            string[] tagsOfScenario = new string[] {
                    "lifecycle",
                    "activation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reactivate a suspended tenant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 25
        testRunner.Given("the tenant is suspended with reason \"Payment overdue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 26
        testRunner.When("I activate the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 27
        testRunner.Then("the tenant status should be \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 28
        testRunner.And("the suspension reason should be cleared", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 29
        testRunner.And("a TenantActivated domain event should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Suspend an active tenant")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Lifecycle Management")]
        [Xunit.TraitAttribute("Description", "Suspend an active tenant")]
        [Xunit.TraitAttribute("Category", "lifecycle")]
        [Xunit.TraitAttribute("Category", "suspension")]
        public void SuspendAnActiveTenant()
        {
            string[] tagsOfScenario = new string[] {
                    "lifecycle",
                    "suspension"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Suspend an active tenant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 33
        testRunner.When("I suspend the tenant with reason \"Terms of service violation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
        testRunner.Then("the tenant status should be \"Suspended\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
        testRunner.And("the suspension date should be set", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
        testRunner.And("the suspension reason should be \"Terms of service violation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Suspend requires a reason")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Lifecycle Management")]
        [Xunit.TraitAttribute("Description", "Suspend requires a reason")]
        [Xunit.TraitAttribute("Category", "lifecycle")]
        [Xunit.TraitAttribute("Category", "suspension")]
        [Xunit.TraitAttribute("Category", "validation")]
        public void SuspendRequiresAReason()
        {
            string[] tagsOfScenario = new string[] {
                    "lifecycle",
                    "suspension",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Suspend requires a reason", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 40
        testRunner.When("I attempt to suspend the tenant without a reason", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 41
        testRunner.Then("it should throw an ArgumentException for \"reason\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deactivate an active tenant")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Lifecycle Management")]
        [Xunit.TraitAttribute("Description", "Deactivate an active tenant")]
        [Xunit.TraitAttribute("Category", "lifecycle")]
        [Xunit.TraitAttribute("Category", "deactivation")]
        public void DeactivateAnActiveTenant()
        {
            string[] tagsOfScenario = new string[] {
                    "lifecycle",
                    "deactivation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deactivate an active tenant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 45
        testRunner.When("I deactivate the tenant with reason \"Account closed by customer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
        testRunner.Then("the tenant status should be \"Deactivated\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
        testRunner.And("a TenantDeactivated domain event should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deactivate requires a reason")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Lifecycle Management")]
        [Xunit.TraitAttribute("Description", "Deactivate requires a reason")]
        [Xunit.TraitAttribute("Category", "lifecycle")]
        [Xunit.TraitAttribute("Category", "deactivation")]
        [Xunit.TraitAttribute("Category", "validation")]
        public void DeactivateRequiresAReason()
        {
            string[] tagsOfScenario = new string[] {
                    "lifecycle",
                    "deactivation",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deactivate requires a reason", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 51
        testRunner.When("I attempt to deactivate the tenant without a reason", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 52
        testRunner.Then("it should throw an ArgumentException for \"reason\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reactivate a deactivated tenant")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Lifecycle Management")]
        [Xunit.TraitAttribute("Description", "Reactivate a deactivated tenant")]
        [Xunit.TraitAttribute("Category", "lifecycle")]
        [Xunit.TraitAttribute("Category", "deactivation")]
        public void ReactivateADeactivatedTenant()
        {
            string[] tagsOfScenario = new string[] {
                    "lifecycle",
                    "deactivation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reactivate a deactivated tenant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
#line 56
        testRunner.Given("the tenant is deactivated with reason \"Account closed\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
        testRunner.When("I activate the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 58
        testRunner.Then("the tenant status should be \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
        testRunner.And("the suspension reason should be cleared", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 60
        testRunner.And("a TenantActivated domain event should be raised", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Query tenants by active status")]
        [Xunit.TraitAttribute("FeatureTitle", "Tenant Lifecycle Management")]
        [Xunit.TraitAttribute("Description", "Query tenants by active status")]
        [Xunit.TraitAttribute("Category", "lifecycle")]
        [Xunit.TraitAttribute("Category", "query")]
        public void QueryTenantsByActiveStatus()
        {
            string[] tagsOfScenario = new string[] {
                    "lifecycle",
                    "query"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Query tenants by active status", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Identifier",
                            "Status"});
                table1.AddRow(new string[] {
                            "active-one",
                            "Active"});
                table1.AddRow(new string[] {
                            "active-two",
                            "Active"});
                table1.AddRow(new string[] {
                            "suspended-co",
                            "Suspended"});
                table1.AddRow(new string[] {
                            "deactive-co",
                            "Deactivated"});
#line 64
        testRunner.Given("the following tenants exist:", ((string)(null)), table1, "Given ");
#line hidden
#line 70
        testRunner.When("I query tenants with status \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 71
        testRunner.Then("I should get 3 tenants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 72
        testRunner.And("the results should contain \"active-one\" and \"active-two\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TenantLifecycleManagementFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TenantLifecycleManagementFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
